import Head from "next/head";
import {TopCategoryList} from "@/components/category/components/TopCategoryList";
import {CategoryStyles} from "@/components/category/styles/CategoryStyles";

export default function Home() {
  return (
      <>
          <Head>
              <title>Create Next App</title>
              <meta name="description" content="Generated by create next app"/>
              <meta name="viewport" content="width=device-width, initial-scale=1"/>
              <link rel="icon" href="/favicon.ico"/>
          </Head>
          <CategoryStyles>
              <h1>Our Solutions</h1>
              <TopCategoryList/>
          </CategoryStyles>
      </>
  );
}
